// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type CalidadDocumentDataSlicesSlice = never;

/**
 * Content for Calidad documents
 */
interface CalidadDocumentData {
  /**
   * Titulo de prueba field in *Calidad*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Tit
   * - **API ID Path**: calidad.titulo_de_prueba
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titulo_de_prueba: prismic.KeyTextField;

  /**
   * Slice Zone field in *Calidad*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: calidad.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<CalidadDocumentDataSlicesSlice> /**
   * Meta Title field in *Calidad*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: calidad.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Calidad*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: calidad.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Calidad*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: calidad.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Calidad document from Prismic
 *
 * - **API ID**: `calidad`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CalidadDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<CalidadDocumentData>,
    "calidad",
    Lang
  >;

type EmpresaDocumentDataSlicesSlice = HeroSlice;

/**
 * Content for Empresa documents
 */
interface EmpresaDocumentData {
  /**
   * Slice Zone field in *Empresa*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: empresa.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<EmpresaDocumentDataSlicesSlice> /**
   * Meta Title field in *Empresa*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: empresa.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Empresa*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: empresa.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Empresa*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: empresa.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Empresa document from Prismic
 *
 * - **API ID**: `empresa`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type EmpresaDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<EmpresaDocumentData>,
    "empresa",
    Lang
  >;

type HomeDocumentDataSlicesSlice = never;

/**
 * Content for Home documents
 */
interface HomeDocumentData {
  /**
   * Slice Zone field in *Home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice> /**
   * Meta Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, "home", Lang>;

type PageDocumentDataSlicesSlice = ProductShowcaseSlice | HeroSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

type ProductosDocumentDataSlicesSlice = never;

/**
 * Content for Productos documents
 */
interface ProductosDocumentData {
  /**
   * Slice Zone field in *Productos*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: productos.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ProductosDocumentDataSlicesSlice> /**
   * Meta Title field in *Productos*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: productos.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Productos*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: productos.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Productos*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: productos.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Productos document from Prismic
 *
 * - **API ID**: `productos`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProductosDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ProductosDocumentData>,
    "productos",
    Lang
  >;

/**
 * Item in *settings → Contact Section*
 */
export interface SettingsDocumentDataContactSectionItem {
  /**
   * Section Title field in *settings → Contact Section*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Titulo de la seccion
   * - **API ID Path**: settings.contact_section[].section_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  section_title: prismic.KeyTextField;

  /**
   * Direction field in *settings → Contact Section*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Direccion
   * - **API ID Path**: settings.contact_section[].direction
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  direction: prismic.KeyTextField;

  /**
   * Phone number 1 field in *settings → Contact Section*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Numero de Telefono 1
   * - **API ID Path**: settings.contact_section[].phone_number_1
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  phone_number_1: prismic.KeyTextField;

  /**
   * Phone Number 2 field in *settings → Contact Section*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Numero de Telefono 2
   * - **API ID Path**: settings.contact_section[].phone_number_2
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  phone_number_2: prismic.KeyTextField;

  /**
   * Phone Number 3 field in *settings → Contact Section*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Numero de Telefono 3
   * - **API ID Path**: settings.contact_section[].phone_number_3
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  phone_number_3: prismic.KeyTextField;

  /**
   * Email field in *settings → Contact Section*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Direccion de correo electronico
   * - **API ID Path**: settings.contact_section[].email
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  email: prismic.Repeatable<prismic.LinkField>;
}

/**
 * Content for settings documents
 */
interface SettingsDocumentData {
  /**
   * Logo field in *settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<"mobile_logo">;

  /**
   * Red-Deer Logo field in *settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.red_deer_logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  red_deer_logo: prismic.ImageField<"mobile_red_deer_logo">;

  /**
   * Tagline field in *settings*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Texto debajo de los logos en el Footer
   * - **API ID Path**: settings.tagline
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  tagline: prismic.RichTextField;

  /**
   * buttonLink field in *settings*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Link del button en el Header
   * - **API ID Path**: settings.buttonlink
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  buttonlink: prismic.Repeatable<prismic.LinkField>;

  /**
   * Site title field in *settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Titulo del sitio
   * - **API ID Path**: settings.site_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  site_title: prismic.KeyTextField;

  /**
   * Meta Description field in *settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: meta description for SEO
   * - **API ID Path**: settings.meta_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Navigation Link field in *settings*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Link de Navegacion
   * - **API ID Path**: settings.navigation_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  navigation_link: prismic.Repeatable<prismic.LinkField>;

  /**
   * Contact Section field in *settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.contact_section[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  contact_section: prismic.GroupField<
    Simplify<SettingsDocumentDataContactSectionItem>
  >;

  /**
   * Social Media Link field in *settings*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Link Redes Sociales
   * - **API ID Path**: settings.social_media_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  social_media_link: prismic.Repeatable<prismic.LinkField>;

  /**
   * Legal  field in *settings*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: @ Todos los derechos reservados
   * - **API ID Path**: settings.legal
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  legal: prismic.RichTextField;
}

/**
 * settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    "settings",
    Lang
  >;

export type AllDocumentTypes =
  | CalidadDocument
  | EmpresaDocument
  | HomeDocument
  | PageDocument
  | ProductosDocument
  | SettingsDocument;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Full Screen Background Image field in *Hero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.full_screen_background_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  full_screen_background_image: prismic.ImageField<never>;

  /**
   * Heading field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Titulo del Hero
   * - **API ID Path**: hero.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Hero Description field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Descripcion del Hero
   * - **API ID Path**: hero.default.primary.hero_description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  hero_description: prismic.RichTextField;

  /**
   * Hero Link field in *Hero → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Link/Button del Hero
   * - **API ID Path**: hero.default.primary.hero_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  hero_link: prismic.Repeatable<prismic.LinkField>;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Hero → Hero - With Gradient  → Primary*
 */
export interface HeroSliceHeroWithGradientPrimary {
  /**
   * Full Screen Background Image field in *Hero → Hero - With Gradient  → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.heroWithGradient.primary.full_screen_background_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  full_screen_background_image: prismic.ImageField<never>;

  /**
   * Heading field in *Hero → Hero - With Gradient  → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Titulo del Hero
   * - **API ID Path**: hero.heroWithGradient.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Hero Description field in *Hero → Hero - With Gradient  → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Descripcion del Hero
   * - **API ID Path**: hero.heroWithGradient.primary.hero_description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  hero_description: prismic.RichTextField;
}

/**
 * Hero - With Gradient  variation for Hero Slice
 *
 * - **API ID**: `heroWithGradient`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceHeroWithGradient = prismic.SharedSliceVariation<
  "heroWithGradient",
  Simplify<HeroSliceHeroWithGradientPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault | HeroSliceHeroWithGradient;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *ProductShowcase → Default → Primary*
 */
export interface ProductShowcaseSliceDefaultPrimary {
  /**
   * Decorative Text field in *ProductShowcase → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Texto Decorativo
   * - **API ID Path**: product_showcase.default.primary.decorative_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  decorative_text: prismic.KeyTextField;

  /**
   * Main Heading field in *ProductShowcase → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Titulo de la seccion
   * - **API ID Path**: product_showcase.default.primary.main_heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  main_heading: prismic.KeyTextField;
}

/**
 * Default variation for ProductShowcase Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProductShowcaseSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProductShowcaseSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ProductShowcase*
 */
type ProductShowcaseSliceVariation = ProductShowcaseSliceDefault;

/**
 * ProductShowcase Shared Slice
 *
 * - **API ID**: `product_showcase`
 * - **Description**: ProductShowcase
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProductShowcaseSlice = prismic.SharedSlice<
  "product_showcase",
  ProductShowcaseSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      CalidadDocument,
      CalidadDocumentData,
      CalidadDocumentDataSlicesSlice,
      EmpresaDocument,
      EmpresaDocumentData,
      EmpresaDocumentDataSlicesSlice,
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      ProductosDocument,
      ProductosDocumentData,
      ProductosDocumentDataSlicesSlice,
      SettingsDocument,
      SettingsDocumentData,
      SettingsDocumentDataContactSectionItem,
      AllDocumentTypes,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceHeroWithGradientPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      HeroSliceHeroWithGradient,
      ProductShowcaseSlice,
      ProductShowcaseSliceDefaultPrimary,
      ProductShowcaseSliceVariation,
      ProductShowcaseSliceDefault,
    };
  }
}
