// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type CalidadDocumentDataSlicesSlice = HeroSlice;

/**
 * Content for Calidad documents
 */
interface CalidadDocumentData {
  /**
   * Slice Zone field in *Calidad*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: calidad.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<CalidadDocumentDataSlicesSlice> /**
   * Meta Title field in *Calidad*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: calidad.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Calidad*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: calidad.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Calidad*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: calidad.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Calidad document from Prismic
 *
 * - **API ID**: `calidad`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CalidadDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<CalidadDocumentData>,
    "calidad",
    Lang
  >;

type ContactanosDocumentDataSlicesSlice = HeroSlice;

/**
 * Content for Contactanos documents
 */
interface ContactanosDocumentData {
  /**
   * Page Description field in *Contactanos*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Descripcion de la Pagina
   * - **API ID Path**: contactanos.page_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  page_description: prismic.RichTextField;

  /**
   * Slice Zone field in *Contactanos*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: contactanos.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ContactanosDocumentDataSlicesSlice> /**
   * Meta Title field in *Contactanos*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: contactanos.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Contactanos*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: contactanos.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Contactanos*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: contactanos.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Contactanos document from Prismic
 *
 * - **API ID**: `contactanos`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ContactanosDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ContactanosDocumentData>,
    "contactanos",
    Lang
  >;

type EmpresaDocumentDataSlicesSlice =
  | BrandShowcaseSlice
  | ProductionFacilitiesSlice
  | CompanyValuesSlice
  | CompanyOverviewSlice
  | HeroSlice;

/**
 * Content for Empresa documents
 */
interface EmpresaDocumentData {
  /**
   * Slice Zone field in *Empresa*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: empresa.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<EmpresaDocumentDataSlicesSlice> /**
   * Meta Title field in *Empresa*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: empresa.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Empresa*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: empresa.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Empresa*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: empresa.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Empresa document from Prismic
 *
 * - **API ID**: `empresa`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type EmpresaDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<EmpresaDocumentData>,
    "empresa",
    Lang
  >;

type HomeDocumentDataSlicesSlice = never;

/**
 * Content for Home documents
 */
interface HomeDocumentData {
  /**
   * Slice Zone field in *Home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice> /**
   * Meta Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, "home", Lang>;

type PageDocumentDataSlicesSlice =
  | TextWithMediaSlice
  | ProductShowcaseSlice
  | HeroSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

/**
 * Item in *Product → Product Varieties*
 */
export interface ProductDocumentDataProductVarietiesItem {
  /**
   * Product Var Image field in *Product → Product Varieties*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: product.product_varieties[].product_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  product_image: prismic.ImageField<never>;

  /**
   * Product Var Code field in *Product → Product Varieties*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Codigo de la va del producto
   * - **API ID Path**: product.product_varieties[].product_var_code
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  product_var_code: prismic.KeyTextField;

  /**
   * Product Var Type field in *Product → Product Varieties*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Tipo de var de producto
   * - **API ID Path**: product.product_varieties[].product_var_type
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  product_var_type: prismic.KeyTextField;

  /**
   * Product Var Weight field in *Product → Product Varieties*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Peso de la var del producto
   * - **API ID Path**: product.product_varieties[].product_var_weight
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  product_var_weight: prismic.KeyTextField;

  /**
   * Product Var Lifespan field in *Product → Product Varieties*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Esperanza de vida de la var. del producto
   * - **API ID Path**: product.product_varieties[].product_var_lifespan
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  product_var_lifespan: prismic.KeyTextField;

  /**
   * Product Var Quantity per box field in *Product → Product Varieties*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Cantidad por caja de la var del producto
   * - **API ID Path**: product.product_varieties[].product_var_quantity_per_box
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  product_var_quantity_per_box: prismic.KeyTextField;

  /**
   * Product Var Weight per box  field in *Product → Product Varieties*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Peso de la cara de la var del product
   * - **API ID Path**: product.product_varieties[].product_var_weight_per_box
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  product_var_weight_per_box: prismic.KeyTextField;
}

/**
 * Content for Product documents
 */
interface ProductDocumentData {
  /**
   * Product Image field in *Product*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: product.product_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  product_image: prismic.ImageField<never>;

  /**
   * Product Title field in *Product*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Titulo del producto
   * - **API ID Path**: product.product_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  product_title: prismic.KeyTextField;

  /**
   * Button Link field in *Product*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Link a la pagina del producto
   * - **API ID Path**: product.button_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField;

  /**
   * Product Varieties field in *Product*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: product.product_varieties[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  product_varieties: prismic.GroupField<
    Simplify<ProductDocumentDataProductVarietiesItem>
  >;
}

/**
 * Product document from Prismic
 *
 * - **API ID**: `product`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProductDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ProductDocumentData>,
    "product",
    Lang
  >;

interface ProductListDocumentData {}

/**
 * Product List document from Prismic
 *
 * - **API ID**: `product_list`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProductListDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ProductListDocumentData>,
    "product_list",
    Lang
  >;

type ProductosDocumentDataSlicesSlice = never;

/**
 * Content for Productos documents
 */
interface ProductosDocumentData {
  /**
   * Slice Zone field in *Productos*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: productos.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ProductosDocumentDataSlicesSlice> /**
   * Meta Title field in *Productos*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: productos.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Productos*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: productos.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Productos*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: productos.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Productos document from Prismic
 *
 * - **API ID**: `productos`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProductosDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ProductosDocumentData>,
    "productos",
    Lang
  >;

/**
 * Item in *settings → Contact Section*
 */
export interface SettingsDocumentDataContactSectionItem {
  /**
   * Section Title field in *settings → Contact Section*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Titulo de la seccion
   * - **API ID Path**: settings.contact_section[].section_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  section_title: prismic.KeyTextField;

  /**
   * Direction field in *settings → Contact Section*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Direccion
   * - **API ID Path**: settings.contact_section[].direction
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  direction: prismic.KeyTextField;

  /**
   * Phone number 1 field in *settings → Contact Section*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Numero de Telefono 1
   * - **API ID Path**: settings.contact_section[].phone_number_1
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  phone_number_1: prismic.KeyTextField;

  /**
   * Phone Number 2 field in *settings → Contact Section*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Numero de Telefono 2
   * - **API ID Path**: settings.contact_section[].phone_number_2
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  phone_number_2: prismic.KeyTextField;

  /**
   * Phone Number 3 field in *settings → Contact Section*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Numero de Telefono 3
   * - **API ID Path**: settings.contact_section[].phone_number_3
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  phone_number_3: prismic.KeyTextField;

  /**
   * Email field in *settings → Contact Section*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Direccion de correo electronico
   * - **API ID Path**: settings.contact_section[].email
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  email: prismic.Repeatable<prismic.LinkField>;
}

/**
 * Content for settings documents
 */
interface SettingsDocumentData {
  /**
   * Logo field in *settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<"mobile_logo">;

  /**
   * Red-Deer Logo field in *settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.red_deer_logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  red_deer_logo: prismic.ImageField<"mobile_red_deer_logo">;

  /**
   * Tagline field in *settings*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Texto debajo de los logos en el Footer
   * - **API ID Path**: settings.tagline
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  tagline: prismic.RichTextField;

  /**
   * buttonLink field in *settings*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Link del button en el Header
   * - **API ID Path**: settings.buttonlink
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  buttonlink: prismic.Repeatable<prismic.LinkField>;

  /**
   * Site title field in *settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Titulo del sitio
   * - **API ID Path**: settings.site_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  site_title: prismic.KeyTextField;

  /**
   * Meta Description field in *settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: meta description for SEO
   * - **API ID Path**: settings.meta_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Navigation Link field in *settings*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Link de Navegacion
   * - **API ID Path**: settings.navigation_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  navigation_link: prismic.Repeatable<prismic.LinkField>;

  /**
   * Contact Section field in *settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.contact_section[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  contact_section: prismic.GroupField<
    Simplify<SettingsDocumentDataContactSectionItem>
  >;

  /**
   * Social Media Link field in *settings*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Link Redes Sociales
   * - **API ID Path**: settings.social_media_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  social_media_link: prismic.Repeatable<prismic.LinkField>;

  /**
   * Legal  field in *settings*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: @ Todos los derechos reservados
   * - **API ID Path**: settings.legal
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  legal: prismic.RichTextField;
}

/**
 * settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    "settings",
    Lang
  >;

export type AllDocumentTypes =
  | CalidadDocument
  | ContactanosDocument
  | EmpresaDocument
  | HomeDocument
  | PageDocument
  | ProductDocument
  | ProductListDocument
  | ProductosDocument
  | SettingsDocument;

/**
 * Primary content in *BrandShowcase → Default → Primary*
 */
export interface BrandShowcaseSliceDefaultPrimary {
  /**
   * Section Title field in *BrandShowcase → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Titulo de la seccion
   * - **API ID Path**: brand_showcase.default.primary.section_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  section_title: prismic.KeyTextField;

  /**
   * Section Description field in *BrandShowcase → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Descripcion de la seccion | Descripcion sobre RedDeer
   * - **API ID Path**: brand_showcase.default.primary.section_description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  section_description: prismic.RichTextField;

  /**
   * Lambare Logo field in *BrandShowcase → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: brand_showcase.default.primary.lambare_logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  lambare_logo: prismic.ImageField<never>;

  /**
   * LVK logo field in *BrandShowcase → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: brand_showcase.default.primary.lvk_logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  lvk_logo: prismic.ImageField<never>;

  /**
   * 295 Logo field in *BrandShowcase → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: brand_showcase.default.primary.295_logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  "295_logo": prismic.ImageField<never>;
}

/**
 * Default variation for BrandShowcase Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BrandShowcaseSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BrandShowcaseSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *BrandShowcase*
 */
type BrandShowcaseSliceVariation = BrandShowcaseSliceDefault;

/**
 * BrandShowcase Shared Slice
 *
 * - **API ID**: `brand_showcase`
 * - **Description**: BrandShowcase
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BrandShowcaseSlice = prismic.SharedSlice<
  "brand_showcase",
  BrandShowcaseSliceVariation
>;

/**
 * Primary content in *CompanyOverview → Default → Primary*
 */
export interface CompanyOverviewSliceDefaultPrimary {
  /**
   * Company Overview field in *CompanyOverview → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Quienes Somos Title
   * - **API ID Path**: company_overview.default.primary.company_overview
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  company_overview: prismic.KeyTextField;

  /**
   * Company Overview Description field in *CompanyOverview → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Quienes Somos Descripcion
   * - **API ID Path**: company_overview.default.primary.company_overview_description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  company_overview_description: prismic.RichTextField;

  /**
   * Company Logos field in *CompanyOverview → Default → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: company_overview.default.primary.company_logos
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  company_logos: prismic.ContentRelationshipField<"settings">;
}

/**
 * Default variation for CompanyOverview Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CompanyOverviewSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CompanyOverviewSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CompanyOverview*
 */
type CompanyOverviewSliceVariation = CompanyOverviewSliceDefault;

/**
 * CompanyOverview Shared Slice
 *
 * - **API ID**: `company_overview`
 * - **Description**: CompanyOverview
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CompanyOverviewSlice = prismic.SharedSlice<
  "company_overview",
  CompanyOverviewSliceVariation
>;

/**
 * Item in *CompanyValues → Default → Primary → ValuesCard*
 */
export interface CompanyValuesSliceDefaultPrimaryValuescardItem {
  /**
   * Card title field in *CompanyValues → Default → Primary → ValuesCard*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Titulo de la card
   * - **API ID Path**: company_values.default.primary.valuescard[].card_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  card_title: prismic.KeyTextField;

  /**
   * Card Description field in *CompanyValues → Default → Primary → ValuesCard*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Descripcion de la Card
   * - **API ID Path**: company_values.default.primary.valuescard[].card_description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  card_description: prismic.RichTextField;
}

/**
 * Primary content in *CompanyValues → Default → Primary*
 */
export interface CompanyValuesSliceDefaultPrimary {
  /**
   * Section Title field in *CompanyValues → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Titulo de la seccion
   * - **API ID Path**: company_values.default.primary.section_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  section_title: prismic.KeyTextField;

  /**
   * ValuesCard field in *CompanyValues → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: company_values.default.primary.valuescard[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  valuescard: prismic.GroupField<
    Simplify<CompanyValuesSliceDefaultPrimaryValuescardItem>
  >;
}

/**
 * Default variation for CompanyValues Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CompanyValuesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CompanyValuesSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CompanyValues*
 */
type CompanyValuesSliceVariation = CompanyValuesSliceDefault;

/**
 * CompanyValues Shared Slice
 *
 * - **API ID**: `company_values`
 * - **Description**: CompanyValues
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CompanyValuesSlice = prismic.SharedSlice<
  "company_values",
  CompanyValuesSliceVariation
>;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Full Screen Background Image field in *Hero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.full_screen_background_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  full_screen_background_image: prismic.ImageField<never>;

  /**
   * Heading field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Titulo del Hero
   * - **API ID Path**: hero.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Hero Description field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Descripcion del Hero
   * - **API ID Path**: hero.default.primary.hero_description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  hero_description: prismic.RichTextField;

  /**
   * Hero Link field in *Hero → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Link/Button del Hero
   * - **API ID Path**: hero.default.primary.hero_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  hero_link: prismic.Repeatable<prismic.LinkField>;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Hero → Hero - With Gradient  → Primary*
 */
export interface HeroSliceHeroWithGradientPrimary {
  /**
   * Full Screen Background Image field in *Hero → Hero - With Gradient  → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.heroWithGradient.primary.full_screen_background_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  full_screen_background_image: prismic.ImageField<never>;

  /**
   * Heading field in *Hero → Hero - With Gradient  → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Titulo del Hero
   * - **API ID Path**: hero.heroWithGradient.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Hero Description field in *Hero → Hero - With Gradient  → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Descripcion del Hero
   * - **API ID Path**: hero.heroWithGradient.primary.hero_description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  hero_description: prismic.RichTextField;
}

/**
 * Hero - With Gradient  variation for Hero Slice
 *
 * - **API ID**: `heroWithGradient`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceHeroWithGradient = prismic.SharedSliceVariation<
  "heroWithGradient",
  Simplify<HeroSliceHeroWithGradientPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault | HeroSliceHeroWithGradient;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *ProductShowcase → Default → Primary*
 */
export interface ProductShowcaseSliceDefaultPrimary {
  /**
   * Decorative Text field in *ProductShowcase → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Texto Decorativo
   * - **API ID Path**: product_showcase.default.primary.decorative_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  decorative_text: prismic.KeyTextField;

  /**
   * Main Heading field in *ProductShowcase → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Titulo de la seccion
   * - **API ID Path**: product_showcase.default.primary.main_heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  main_heading: prismic.KeyTextField;
}

/**
 * Default variation for ProductShowcase Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProductShowcaseSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProductShowcaseSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ProductShowcase*
 */
type ProductShowcaseSliceVariation = ProductShowcaseSliceDefault;

/**
 * ProductShowcase Shared Slice
 *
 * - **API ID**: `product_showcase`
 * - **Description**: ProductShowcase
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProductShowcaseSlice = prismic.SharedSlice<
  "product_showcase",
  ProductShowcaseSliceVariation
>;

/**
 * Item in *ProductionFacilities → Default → Primary → facilities*
 */
export interface ProductionFacilitiesSliceDefaultPrimaryFacilitiesItem {
  /**
   * Title field in *ProductionFacilities → Default → Primary → facilities*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Titulo
   * - **API ID Path**: production_facilities.default.primary.facilities[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *ProductionFacilities → Default → Primary → facilities*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Descripcion
   * - **API ID Path**: production_facilities.default.primary.facilities[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Imagen field in *ProductionFacilities → Default → Primary → facilities*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: production_facilities.default.primary.facilities[].imagen
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imagen: prismic.ImageField<never>;
}

/**
 * Primary content in *ProductionFacilities → Default → Primary*
 */
export interface ProductionFacilitiesSliceDefaultPrimary {
  /**
   * Section Title Start field in *ProductionFacilities → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Comienzo del titulo de la seccion
   * - **API ID Path**: production_facilities.default.primary.section_title_start
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  section_title_start: prismic.KeyTextField;

  /**
   * Highlighted Word field in *ProductionFacilities → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Palabra especifica del titulo en Rojo
   * - **API ID Path**: production_facilities.default.primary.highlighted_word
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  highlighted_word: prismic.KeyTextField;

  /**
   * Section Title End field in *ProductionFacilities → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Final del titulo de la seccion
   * - **API ID Path**: production_facilities.default.primary.section_title_end
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  section_title_end: prismic.KeyTextField;

  /**
   * facilities field in *ProductionFacilities → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: production_facilities.default.primary.facilities[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  facilities: prismic.GroupField<
    Simplify<ProductionFacilitiesSliceDefaultPrimaryFacilitiesItem>
  >;
}

/**
 * Default variation for ProductionFacilities Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProductionFacilitiesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProductionFacilitiesSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ProductionFacilities*
 */
type ProductionFacilitiesSliceVariation = ProductionFacilitiesSliceDefault;

/**
 * ProductionFacilities Shared Slice
 *
 * - **API ID**: `production_facilities`
 * - **Description**: ProductionFacilities
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProductionFacilitiesSlice = prismic.SharedSlice<
  "production_facilities",
  ProductionFacilitiesSliceVariation
>;

/**
 * Primary content in *TextWithMedia → Default → Primary*
 */
export interface TextWithMediaSliceDefaultPrimary {
  /**
   * Imagen field in *TextWithMedia → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: text_with_media.default.primary.imagen
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imagen: prismic.ImageField<"tablet" | "mobile">;

  /**
   * Decorative Text field in *TextWithMedia → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Texto Decorativo
   * - **API ID Path**: text_with_media.default.primary.decorative_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  decorative_text: prismic.KeyTextField;

  /**
   * Section Title field in *TextWithMedia → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Titulo de la seccion
   * - **API ID Path**: text_with_media.default.primary.section_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  section_title: prismic.KeyTextField;

  /**
   * Section Description field in *TextWithMedia → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Descripcion de la seccion
   * - **API ID Path**: text_with_media.default.primary.section_description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  section_description: prismic.RichTextField;

  /**
   * Button Link field in *TextWithMedia → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Link del CTA | Button
   * - **API ID Path**: text_with_media.default.primary.button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField;
}

/**
 * Default variation for TextWithMedia Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextWithMediaSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TextWithMediaSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *TextWithMedia → fullWidthImage → Primary*
 */
export interface TextWithMediaSliceFullWidthImagePrimary {
  /**
   * Imagen field in *TextWithMedia → fullWidthImage → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: text_with_media.fullWidthImage.primary.imagen
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imagen: prismic.ImageField<"tablet" | "mobile">;

  /**
   * Decorative Text field in *TextWithMedia → fullWidthImage → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Texto Decorativo
   * - **API ID Path**: text_with_media.fullWidthImage.primary.decorative_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  decorative_text: prismic.KeyTextField;

  /**
   * Section Title field in *TextWithMedia → fullWidthImage → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Titulo de la seccion
   * - **API ID Path**: text_with_media.fullWidthImage.primary.section_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  section_title: prismic.KeyTextField;

  /**
   * Section Description field in *TextWithMedia → fullWidthImage → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Descripcion de la seccion
   * - **API ID Path**: text_with_media.fullWidthImage.primary.section_description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  section_description: prismic.RichTextField;

  /**
   * Button Link field in *TextWithMedia → fullWidthImage → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Link del CTA | Button
   * - **API ID Path**: text_with_media.fullWidthImage.primary.button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField;
}

/**
 * fullWidthImage variation for TextWithMedia Slice
 *
 * - **API ID**: `fullWidthImage`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextWithMediaSliceFullWidthImage = prismic.SharedSliceVariation<
  "fullWidthImage",
  Simplify<TextWithMediaSliceFullWidthImagePrimary>,
  never
>;

/**
 * Slice variation for *TextWithMedia*
 */
type TextWithMediaSliceVariation =
  | TextWithMediaSliceDefault
  | TextWithMediaSliceFullWidthImage;

/**
 * TextWithMedia Shared Slice
 *
 * - **API ID**: `text_with_media`
 * - **Description**: TextWithMedia
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextWithMediaSlice = prismic.SharedSlice<
  "text_with_media",
  TextWithMediaSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      CalidadDocument,
      CalidadDocumentData,
      CalidadDocumentDataSlicesSlice,
      ContactanosDocument,
      ContactanosDocumentData,
      ContactanosDocumentDataSlicesSlice,
      EmpresaDocument,
      EmpresaDocumentData,
      EmpresaDocumentDataSlicesSlice,
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      ProductDocument,
      ProductDocumentData,
      ProductDocumentDataProductVarietiesItem,
      ProductListDocument,
      ProductListDocumentData,
      ProductosDocument,
      ProductosDocumentData,
      ProductosDocumentDataSlicesSlice,
      SettingsDocument,
      SettingsDocumentData,
      SettingsDocumentDataContactSectionItem,
      AllDocumentTypes,
      BrandShowcaseSlice,
      BrandShowcaseSliceDefaultPrimary,
      BrandShowcaseSliceVariation,
      BrandShowcaseSliceDefault,
      CompanyOverviewSlice,
      CompanyOverviewSliceDefaultPrimary,
      CompanyOverviewSliceVariation,
      CompanyOverviewSliceDefault,
      CompanyValuesSlice,
      CompanyValuesSliceDefaultPrimaryValuescardItem,
      CompanyValuesSliceDefaultPrimary,
      CompanyValuesSliceVariation,
      CompanyValuesSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceHeroWithGradientPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      HeroSliceHeroWithGradient,
      ProductShowcaseSlice,
      ProductShowcaseSliceDefaultPrimary,
      ProductShowcaseSliceVariation,
      ProductShowcaseSliceDefault,
      ProductionFacilitiesSlice,
      ProductionFacilitiesSliceDefaultPrimaryFacilitiesItem,
      ProductionFacilitiesSliceDefaultPrimary,
      ProductionFacilitiesSliceVariation,
      ProductionFacilitiesSliceDefault,
      TextWithMediaSlice,
      TextWithMediaSliceDefaultPrimary,
      TextWithMediaSliceFullWidthImagePrimary,
      TextWithMediaSliceVariation,
      TextWithMediaSliceDefault,
      TextWithMediaSliceFullWidthImage,
    };
  }
}
