// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  brand_showcase: dynamic(() => import("./BrandShowcase")),
  company_overview: dynamic(() => import("./CompanyOverview")),
  company_values: dynamic(() => import("./CompanyValues")),
  hero: dynamic(() => import("./Hero")),
  product_showcase: dynamic(() => import("./ProductShowcase")),
  production_facilities: dynamic(() => import("./ProductionFacilities")),
  text_with_media: dynamic(() => import("./TextWithMedia")),
};
